### ISSUE TITLE
Code highlighting colors in mdjs viewer are not in line with normal markdown code blocks

### ISSUE THREAD

**Issue by gerjanvangeest** [modernweb-dev/rocket#87]
I would like to customize some colors of the markdown code blocks, which goes easy with e.g. `--markdown-syntax-color` (and other variables). But this is not possible for the code examples inside mdjs viewer.

If they are in sync i could just assign a color to the variable once.

So i suggest to use the markdown-syntax variables in your code as well:

```css
.token.function,
.token.class-name {
    color: #6f42c1;
}
```

Becomes:

```css
.token.function {
    color: var(--markdown-syntax-function-color, #6f42c1);
}

.token.class-name {
    color: var(--markdown-syntax-class-name-color, #6f42c1);
}
```
